### PR TITLE
Application log main to develop

### PR DESCRIPTION
**Pull request by maxmoneycash**
Max:  Sprint 1 tasks complete

### CODE REVIEW

**Comment by helenewillits** [comment]
looks good! Need to implement some features for the next pull request:
- nested onClick request for Delete and Popup in Application Log
- Requirements on the New Application

**Comment by ShainaBagri** [comment]
Nice job! Need to clean up code by getting rid of commented out code we no longer use.

**Review by helenawillits — COMMENTED** [review]
looks good! Need to implement some features for the next pull request:

nested onClick request for Delete and Popup in Application Log
Requirements on the New Application

**Review by ShainaBagri — COMMENTED** [review]
Nice job! Need to clean up code by getting rid of commented out code we no longer use.

**Comment by pipfeld** [comment]
Looks good - make sure all commit messages are descriptive!

**Review by pipfeld — APPROVED** [review]
Looks good - make sure all commit messages are relevant and descriptive!

**Review by ShainaBagri — APPROVED** [review]

**Pull request merged**
